# Generated by Django 3.2.5 on 2021-08-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50)),
                ('assembly', models.CharField(max_length=100)),
                ('line_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Lines',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=200)),
                ('line', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='history.linehistory', verbose_name='Lines')),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_num', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('work_done', models.TextField(blank=True)),
                ('carrier_slug', models.CharField(default=1, max_length=200)),
                ('history', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='history.history')),
            ],
        ),
    ]
