# Generated by Django 3.2.5 on 2021-08-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='changed_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
