# Generated by Django 3.2.5 on 2021-08-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_carrier_greasing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_num', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='carrier',
            name='carrier_slug',
            field=models.SlugField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='carrier_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='history.carrier_num'),
        ),
    ]
