# Generated by Django 3.2.5 on 2021-08-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20210803_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrier_num',
            new_name='Carrier_number',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='history',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
