# Generated by Django 3.2.5 on 2021-08-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_auto_20210804_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='greasing',
        ),
        migrations.AddField(
            model_name='carrier_number',
            name='greasing',
            field=models.CharField(choices=[('ultra', 'Ultra'), ('premier', 'Premier')], default='premier', max_length=10),
        ),
    ]
