# Generated by Django 3.2.5 on 2021-08-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_auto_20210804_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='front_kingpin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='front_pickup_trolly',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='front_rear_trolly',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='rear_kingpin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='rear_nonpickup_trolly',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='rear_pickup_trolly',
            field=models.DateField(blank=True, null=True),
        ),
    ]
