# Generated by Django 3.2.9 on 2022-01-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_auto_20210805_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_numbers', models.IntegerField(max_length=2)),
                ('stop_type', models.CharField(choices=[('oven', 'Oven'), ('lh', 'Lh'), ('rh', 'Rh')], default='lh', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tsw_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsw_number', models.IntegerField(max_length=2)),
                ('tsw_type', models.CharField(choices=[('tsw', 'Tsw'), ('retrocate', 'Retrocate')], default='retrocate', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tsw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearing_change_date', models.DateField()),
                ('work_done', models.CharField(max_length=100)),
                ('work_done_date', models.DateTimeField(auto_now_add=True)),
                ('tsw', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='history.tsw_number')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_date', models.DateField()),
                ('greasing_data', models.DateField()),
                ('work_done', models.CharField(max_length=100)),
                ('work_done_date', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='history.stop_numbers')),
            ],
        ),
    ]
