# Generated by Django 3.2.9 on 2022-01-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_stop_stop_numbers_tsw_tsw_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop_numbers',
            name='stop_numbers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tsw_number',
            name='tsw_number',
            field=models.IntegerField(),
        ),
    ]
