# Generated by Django 3.2.9 on 2022-01-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0013_auto_20220113_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='greasing_data',
            new_name='greasing_date',
        ),
        migrations.RenameField(
            model_name='stop_numbers',
            old_name='stop_numbers',
            new_name='stop_number',
        ),
    ]
