# Generated by Django 3.2.9 on 2022-01-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0015_auto_20220121_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='sub_assembly',
        ),
        migrations.AlterField(
            model_name='types',
            name='part',
            field=models.CharField(choices=[('bearing', 'Bearing'), ('blade', 'Blade'), ('front pickup trolly', 'Front Pickup Trolly'), ('front non pickup trolly', 'Front Non pickup trolly'), ('rear pickup trolly', 'Rear Pickup Trolly'), ('rear non pickup trolly', 'Rear Non pickup trolly'), ('valve', 'Valve'), ('Cylinder', 'Cylinder')], default='Bearing', max_length=25),
        ),
    ]
