# Generated by Django 3.2.9 on 2022-01-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0017_auto_20220121_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
